---
- name: Download Wordpress
  get_url:
    url: '{{ wordpress_download_path }}'
    dest: '{{ wordpress_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    validate_certs: no

- name: Unpack Wordpress
  unarchive:
    src: '{{ wordpress_document_root }}/latest.tar.gz'
    dest: '{{ wordpress_document_root }}'
    owner: 'www-data'
    group: 'www-data'
    copy: no

- name: Copy Core Files
  shell:
    'cp -R {{ wordpress_document_root }}/wordpress/{{ item }} {{ wordpress_document_root }}/'
  args:
    chdir: '{{ wordpress_document_root }}'
  with_items:
    - '*'

- name: Rename config sample
  shell:
    'mv {{ wordpress_document_root }}/wp-config-sample.php {{ wordpress_document_root }}/wp-config.php'

- name: Change chown
  shell:
    'chown -R www-data:www-data {{ wordpress_document_root }}/{{ item }}'
  args:
    chdir: '{{ wordpress_document_root }}'
  with_items:
    - '*'

- name: restart nginx
  service: name=nginx state=restarted

- name: Delete Garbage Files
  file:
    path: '{{ wordpress_document_root }}/{{ item }}'
    state: absent
  with_items:
    wordpress_garbage_files

- name: Add database name to config
  shell:
    'sed -i s/database_name_here/{{ db_name }}/ {{ wordpress_document_root }}/wp-config.php'

- name: Add username name to config
  shell:
    'sed -i s/username_here/{{ db_username }}/ {{ wordpress_document_root }}/wp-config.php'

- name: Add password to config
  shell:
    'sed -i s/password_here/{{ db_password }}/ {{ wordpress_document_root }}/wp-config.php'

- name: add hostname to /etc/hosts
  lineinfile:
    dest=/etc/hosts
    line='{{ host_name }} {{ vhost_name }}'
    regexp='^10\.0\.0*'
    insertafter='^127\.0\.0\.1'
    state=present

- name: Install wordpress
  shell:
    'curl --data "user_name=admin&password=123&password2=123&admin_email=asd@asd.com" http://{{ vhost_name }}:81/wp-admin/install.php?step=2'

- name: Generate Sample Data
  shell:
    '/etc/ansible/roles/generate_sample.sh'

- name: Import Sample Data to DB
  shell:
    "mysql --local-infile wordpress -e \"LOAD DATA LOCAL INFILE '/tmp/wordpress' INTO TABLE wp_posts FIELDS TERMINATED BY ',' (post_author,post_title,post_name,post_type,post_content);\""